// <auto-generated />
using System;
using Imi.Project.Api.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Imi.Project.Api.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Imi.Project.Api.Core.Entities.Arena", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsWon")
                        .HasColumnType("bit");

                    b.Property<Guid>("LeaderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LeaderId");

                    b.ToTable("Arenas");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0001-0000-0000-000000000000"),
                            Date = new DateTime(2021, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsWon = true,
                            LeaderId = new Guid("00000000-0000-0000-0010-000000000000")
                        },
                        new
                        {
                            Id = new Guid("00000000-0002-0000-0000-000000000000"),
                            Date = new DateTime(2021, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsWon = true,
                            LeaderId = new Guid("00000000-0000-0000-0010-000000000000")
                        },
                        new
                        {
                            Id = new Guid("00000000-0003-0000-0000-000000000000"),
                            Date = new DateTime(2021, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsWon = false,
                            LeaderId = new Guid("00000000-0000-0000-0010-000000000000")
                        },
                        new
                        {
                            Id = new Guid("00000000-0004-0000-0000-000000000000"),
                            Date = new DateTime(2021, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsWon = true,
                            LeaderId = new Guid("00000000-0000-0000-0010-000000000000")
                        },
                        new
                        {
                            Id = new Guid("00000000-0005-0000-0000-000000000000"),
                            Date = new DateTime(2021, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsWon = false,
                            LeaderId = new Guid("00000000-0000-0000-0018-000000000000")
                        },
                        new
                        {
                            Id = new Guid("00000000-0006-0000-0000-000000000000"),
                            Date = new DateTime(2021, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsWon = false,
                            LeaderId = new Guid("00000000-0000-0000-0018-000000000000")
                        },
                        new
                        {
                            Id = new Guid("00000000-0007-0000-0000-000000000000"),
                            Date = new DateTime(2021, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsWon = true,
                            LeaderId = new Guid("00000000-0000-0000-0018-000000000000")
                        },
                        new
                        {
                            Id = new Guid("00000000-0008-0000-0000-000000000000"),
                            Date = new DateTime(2021, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsWon = false,
                            LeaderId = new Guid("00000000-0000-0000-0018-000000000000")
                        },
                        new
                        {
                            Id = new Guid("00000000-0009-0000-0000-000000000000"),
                            Date = new DateTime(2021, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsWon = false,
                            LeaderId = new Guid("00000000-0000-0000-0018-000000000000")
                        },
                        new
                        {
                            Id = new Guid("00000000-0010-0000-0000-000000000000"),
                            Date = new DateTime(2021, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsWon = false,
                            LeaderId = new Guid("00000000-0000-0000-0018-000000000000")
                        });
                });

            modelBuilder.Entity("Imi.Project.Api.Core.Entities.ArenaCharacter", b =>
                {
                    b.Property<Guid>("ArenaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ArenaId", "CharacterId");

                    b.HasIndex("CharacterId");

                    b.ToTable("ArenaCharacter");

                    b.HasData(
                        new
                        {
                            ArenaId = new Guid("00000000-0001-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0008-000000000000")
                        },
                        new
                        {
                            ArenaId = new Guid("00000000-0002-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0008-000000000000")
                        },
                        new
                        {
                            ArenaId = new Guid("00000000-0003-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0008-000000000000")
                        },
                        new
                        {
                            ArenaId = new Guid("00000000-0004-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0008-000000000000")
                        },
                        new
                        {
                            ArenaId = new Guid("00000000-0005-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0002-000000000000")
                        },
                        new
                        {
                            ArenaId = new Guid("00000000-0005-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0005-000000000000")
                        },
                        new
                        {
                            ArenaId = new Guid("00000000-0006-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0002-000000000000")
                        },
                        new
                        {
                            ArenaId = new Guid("00000000-0006-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0005-000000000000")
                        },
                        new
                        {
                            ArenaId = new Guid("00000000-0007-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0002-000000000000")
                        },
                        new
                        {
                            ArenaId = new Guid("00000000-0007-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0005-000000000000")
                        },
                        new
                        {
                            ArenaId = new Guid("00000000-0008-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0002-000000000000")
                        },
                        new
                        {
                            ArenaId = new Guid("00000000-0008-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0005-000000000000")
                        },
                        new
                        {
                            ArenaId = new Guid("00000000-0009-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0002-000000000000")
                        },
                        new
                        {
                            ArenaId = new Guid("00000000-0009-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0024-000000000000")
                        },
                        new
                        {
                            ArenaId = new Guid("00000000-0010-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0002-000000000000")
                        },
                        new
                        {
                            ArenaId = new Guid("00000000-0010-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0024-000000000000")
                        });
                });

            modelBuilder.Entity("Imi.Project.Api.Core.Entities.Battleground", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("InstanceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsWon")
                        .HasColumnType("bit");

                    b.Property<Guid>("LeaderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LeaderId");

                    b.ToTable("Battlegrounds");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0001-0000-000000000000"),
                            Date = new DateTime(2021, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstanceName = "Warsong Gulch",
                            IsWon = true,
                            LeaderId = new Guid("00000000-0000-0000-0022-000000000000")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0002-0000-000000000000"),
                            Date = new DateTime(2021, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstanceName = "Twin Peaks",
                            IsWon = true,
                            LeaderId = new Guid("00000000-0000-0000-0022-000000000000")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0003-0000-000000000000"),
                            Date = new DateTime(2021, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstanceName = "Twin Peaks",
                            IsWon = false,
                            LeaderId = new Guid("00000000-0000-0000-0022-000000000000")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0004-0000-000000000000"),
                            Date = new DateTime(2021, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstanceName = "Twin Peaks",
                            IsWon = true,
                            LeaderId = new Guid("00000000-0000-0000-0022-000000000000")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0005-0000-000000000000"),
                            Date = new DateTime(2021, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstanceName = "Warsong Gulch",
                            IsWon = true,
                            LeaderId = new Guid("00000000-0000-0000-0022-000000000000")
                        });
                });

            modelBuilder.Entity("Imi.Project.Api.Core.Entities.BattlegroundCharacter", b =>
                {
                    b.Property<Guid>("BattlegroundId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BattlegroundId", "CharacterId");

                    b.HasIndex("CharacterId");

                    b.ToTable("BattlegroundCharacter");

                    b.HasData(
                        new
                        {
                            BattlegroundId = new Guid("00000000-0000-0001-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0002-000000000000")
                        },
                        new
                        {
                            BattlegroundId = new Guid("00000000-0000-0001-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0003-000000000000")
                        },
                        new
                        {
                            BattlegroundId = new Guid("00000000-0000-0001-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0004-000000000000")
                        },
                        new
                        {
                            BattlegroundId = new Guid("00000000-0000-0001-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0005-000000000000")
                        },
                        new
                        {
                            BattlegroundId = new Guid("00000000-0000-0001-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0006-000000000000")
                        },
                        new
                        {
                            BattlegroundId = new Guid("00000000-0000-0001-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0007-000000000000")
                        },
                        new
                        {
                            BattlegroundId = new Guid("00000000-0000-0001-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0008-000000000000")
                        },
                        new
                        {
                            BattlegroundId = new Guid("00000000-0000-0001-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0009-000000000000")
                        },
                        new
                        {
                            BattlegroundId = new Guid("00000000-0000-0001-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0010-000000000000")
                        },
                        new
                        {
                            BattlegroundId = new Guid("00000000-0000-0002-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0002-000000000000")
                        },
                        new
                        {
                            BattlegroundId = new Guid("00000000-0000-0002-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0003-000000000000")
                        },
                        new
                        {
                            BattlegroundId = new Guid("00000000-0000-0002-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0004-000000000000")
                        },
                        new
                        {
                            BattlegroundId = new Guid("00000000-0000-0002-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0005-000000000000")
                        },
                        new
                        {
                            BattlegroundId = new Guid("00000000-0000-0002-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0006-000000000000")
                        },
                        new
                        {
                            BattlegroundId = new Guid("00000000-0000-0002-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0007-000000000000")
                        },
                        new
                        {
                            BattlegroundId = new Guid("00000000-0000-0002-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0008-000000000000")
                        },
                        new
                        {
                            BattlegroundId = new Guid("00000000-0000-0002-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0009-000000000000")
                        },
                        new
                        {
                            BattlegroundId = new Guid("00000000-0000-0002-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0010-000000000000")
                        },
                        new
                        {
                            BattlegroundId = new Guid("00000000-0000-0003-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0002-000000000000")
                        },
                        new
                        {
                            BattlegroundId = new Guid("00000000-0000-0003-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0003-000000000000")
                        },
                        new
                        {
                            BattlegroundId = new Guid("00000000-0000-0003-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0004-000000000000")
                        },
                        new
                        {
                            BattlegroundId = new Guid("00000000-0000-0003-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0005-000000000000")
                        },
                        new
                        {
                            BattlegroundId = new Guid("00000000-0000-0003-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0006-000000000000")
                        },
                        new
                        {
                            BattlegroundId = new Guid("00000000-0000-0003-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0007-000000000000")
                        },
                        new
                        {
                            BattlegroundId = new Guid("00000000-0000-0003-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0008-000000000000")
                        },
                        new
                        {
                            BattlegroundId = new Guid("00000000-0000-0003-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0009-000000000000")
                        },
                        new
                        {
                            BattlegroundId = new Guid("00000000-0000-0003-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0010-000000000000")
                        },
                        new
                        {
                            BattlegroundId = new Guid("00000000-0000-0004-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0002-000000000000")
                        },
                        new
                        {
                            BattlegroundId = new Guid("00000000-0000-0004-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0003-000000000000")
                        },
                        new
                        {
                            BattlegroundId = new Guid("00000000-0000-0004-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0004-000000000000")
                        },
                        new
                        {
                            BattlegroundId = new Guid("00000000-0000-0004-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0005-000000000000")
                        },
                        new
                        {
                            BattlegroundId = new Guid("00000000-0000-0004-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0006-000000000000")
                        },
                        new
                        {
                            BattlegroundId = new Guid("00000000-0000-0004-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0007-000000000000")
                        },
                        new
                        {
                            BattlegroundId = new Guid("00000000-0000-0004-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0008-000000000000")
                        },
                        new
                        {
                            BattlegroundId = new Guid("00000000-0000-0004-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0030-000000000000")
                        },
                        new
                        {
                            BattlegroundId = new Guid("00000000-0000-0004-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            BattlegroundId = new Guid("00000000-0000-0005-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0002-000000000000")
                        },
                        new
                        {
                            BattlegroundId = new Guid("00000000-0000-0005-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0003-000000000000")
                        },
                        new
                        {
                            BattlegroundId = new Guid("00000000-0000-0005-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0004-000000000000")
                        },
                        new
                        {
                            BattlegroundId = new Guid("00000000-0000-0005-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0005-000000000000")
                        },
                        new
                        {
                            BattlegroundId = new Guid("00000000-0000-0005-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0006-000000000000")
                        },
                        new
                        {
                            BattlegroundId = new Guid("00000000-0000-0005-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0007-000000000000")
                        },
                        new
                        {
                            BattlegroundId = new Guid("00000000-0000-0005-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0008-000000000000")
                        },
                        new
                        {
                            BattlegroundId = new Guid("00000000-0000-0005-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0030-000000000000")
                        },
                        new
                        {
                            BattlegroundId = new Guid("00000000-0000-0005-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0000-000000000010")
                        });
                });

            modelBuilder.Entity("Imi.Project.Api.Core.Entities.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("ArenaRating")
                        .HasColumnType("float");

                    b.Property<double>("BattlegroundRating")
                        .HasColumnType("float");

                    b.Property<string>("Class")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemLevel")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000000"),
                            ArenaRating = 0.0,
                            BattlegroundRating = 0.0,
                            Class = "Death Knight",
                            ItemLevel = 167,
                            Level = 60,
                            Name = "Ghortak",
                            Role = "Tank",
                            UserId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000000"),
                            ArenaRating = 0.0,
                            BattlegroundRating = 0.0,
                            Class = "Druid",
                            ItemLevel = 216,
                            Level = 60,
                            Name = "Bauglir",
                            Role = "Dps",
                            UserId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000000"),
                            ArenaRating = 384.0,
                            BattlegroundRating = 192.0,
                            Class = "Priest",
                            ItemLevel = 131,
                            Level = 60,
                            Name = "Shiroe",
                            Role = "Healer",
                            UserId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000000"),
                            ArenaRating = 0.0,
                            BattlegroundRating = 0.0,
                            Class = "Shaman",
                            ItemLevel = 216,
                            Level = 60,
                            Name = "Yoriko",
                            Role = "Healer",
                            UserId = new Guid("00000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000000"),
                            ArenaRating = 0.0,
                            BattlegroundRating = 0.0,
                            Class = "Warlock",
                            ItemLevel = 149,
                            Level = 60,
                            Name = "Elen",
                            Role = "Dps",
                            UserId = new Guid("00000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0006-000000000000"),
                            ArenaRating = 0.0,
                            BattlegroundRating = 0.0,
                            Class = "Mage",
                            ItemLevel = 187,
                            Level = 60,
                            Name = "Tary",
                            Role = "Dps",
                            UserId = new Guid("00000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0007-000000000000"),
                            ArenaRating = 0.0,
                            BattlegroundRating = 0.0,
                            Class = "Warrior",
                            ItemLevel = 175,
                            Level = 60,
                            Name = "Borugor",
                            Role = "Dps",
                            UserId = new Guid("00000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0008-000000000000"),
                            ArenaRating = 0.0,
                            BattlegroundRating = 0.0,
                            Class = "Hunter",
                            ItemLevel = 196,
                            Level = 60,
                            Name = "Wildstrider",
                            Role = "Dps",
                            UserId = new Guid("00000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0009-000000000000"),
                            ArenaRating = 0.0,
                            BattlegroundRating = 0.0,
                            Class = "Paladin",
                            ItemLevel = 200,
                            Level = 60,
                            Name = "Liutasil",
                            Role = "Tank",
                            UserId = new Guid("00000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0010-000000000000"),
                            ArenaRating = 0.0,
                            BattlegroundRating = 0.0,
                            Class = "Demon Hunter",
                            ItemLevel = 145,
                            Level = 60,
                            Name = "Aerenthil",
                            Role = "Dps",
                            UserId = new Guid("00000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0011-000000000000"),
                            ArenaRating = 0.0,
                            BattlegroundRating = 0.0,
                            Class = "Monk",
                            ItemLevel = 193,
                            Level = 60,
                            Name = "Ghinin",
                            Role = "Tank",
                            UserId = new Guid("00000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0012-000000000000"),
                            ArenaRating = 0.0,
                            BattlegroundRating = 0.0,
                            Class = "Mage",
                            ItemLevel = 145,
                            Level = 60,
                            Name = "Nuremor",
                            Role = "Dps",
                            UserId = new Guid("00000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0013-000000000000"),
                            ArenaRating = 0.0,
                            BattlegroundRating = 0.0,
                            Class = "Shaman",
                            ItemLevel = 185,
                            Level = 60,
                            Name = "Rhamanji",
                            Role = "Dps",
                            UserId = new Guid("00000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0014-000000000000"),
                            ArenaRating = 0.0,
                            BattlegroundRating = 0.0,
                            Class = "Priest",
                            ItemLevel = 187,
                            Level = 60,
                            Name = "Ebrothil",
                            Role = "Dps",
                            UserId = new Guid("00000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0015-000000000000"),
                            ArenaRating = 0.0,
                            BattlegroundRating = 0.0,
                            Class = "Rogue",
                            ItemLevel = 187,
                            Level = 60,
                            Name = "Tyrigon",
                            Role = "Dps",
                            UserId = new Guid("00000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0016-000000000000"),
                            ArenaRating = 0.0,
                            BattlegroundRating = 0.0,
                            Class = "Paladin",
                            ItemLevel = 202,
                            Level = 60,
                            Name = "Aeternus",
                            Role = "Healer",
                            UserId = new Guid("00000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0017-000000000000"),
                            ArenaRating = 0.0,
                            BattlegroundRating = 0.0,
                            Class = "Monk",
                            ItemLevel = 201,
                            Level = 60,
                            Name = "Trech",
                            Role = "Healer",
                            UserId = new Guid("00000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0018-000000000000"),
                            ArenaRating = 0.0,
                            BattlegroundRating = 0.0,
                            Class = "Shaman",
                            ItemLevel = 201,
                            Level = 60,
                            Name = "Baradhor",
                            Role = "Healer",
                            UserId = new Guid("00000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0019-000000000000"),
                            ArenaRating = 0.0,
                            BattlegroundRating = 0.0,
                            Class = "Druid",
                            ItemLevel = 199,
                            Level = 60,
                            Name = "Eranthil",
                            Role = "Healer",
                            UserId = new Guid("00000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0020-000000000000"),
                            ArenaRating = 0.0,
                            BattlegroundRating = 0.0,
                            Class = "Warlock",
                            ItemLevel = 139,
                            Level = 60,
                            Name = "Morgoroth",
                            Role = "Dps",
                            UserId = new Guid("00000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0021-000000000000"),
                            ArenaRating = 0.0,
                            BattlegroundRating = 0.0,
                            Class = "Demon Hunter",
                            ItemLevel = 157,
                            Level = 60,
                            Name = "Malefikh",
                            Role = "Dps",
                            UserId = new Guid("00000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0022-000000000000"),
                            ArenaRating = 0.0,
                            BattlegroundRating = 0.0,
                            Class = "Death Knight",
                            ItemLevel = 187,
                            Level = 60,
                            Name = "Ashifal",
                            Role = "Dps",
                            UserId = new Guid("00000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0023-000000000000"),
                            ArenaRating = 0.0,
                            BattlegroundRating = 0.0,
                            Class = "Hunter",
                            ItemLevel = 188,
                            Level = 60,
                            Name = "Umbrion",
                            Role = "Dps",
                            UserId = new Guid("00000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0024-000000000000"),
                            ArenaRating = 0.0,
                            BattlegroundRating = 0.0,
                            Class = "Mage",
                            ItemLevel = 192,
                            Level = 60,
                            Name = "Coolbone",
                            Role = "Dps",
                            UserId = new Guid("00000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0025-000000000000"),
                            ArenaRating = 0.0,
                            BattlegroundRating = 0.0,
                            Class = "Warrior",
                            ItemLevel = 177,
                            Level = 60,
                            Name = "GilGalad",
                            Role = "Tank",
                            UserId = new Guid("00000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0026-000000000000"),
                            ArenaRating = 0.0,
                            BattlegroundRating = 0.0,
                            Class = "Rogue",
                            ItemLevel = 169,
                            Level = 60,
                            Name = "Yreleth",
                            Role = "Dps",
                            UserId = new Guid("00000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0027-000000000000"),
                            ArenaRating = 0.0,
                            BattlegroundRating = 0.0,
                            Class = "Monk",
                            ItemLevel = 152,
                            Level = 60,
                            Name = "Bromir",
                            Role = "Dps",
                            UserId = new Guid("00000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0028-000000000000"),
                            ArenaRating = 0.0,
                            BattlegroundRating = 0.0,
                            Class = "Druid",
                            ItemLevel = 152,
                            Level = 60,
                            Name = "Phandalor",
                            Role = "Healer",
                            UserId = new Guid("00000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0029-000000000000"),
                            ArenaRating = 0.0,
                            BattlegroundRating = 0.0,
                            Class = "Hunter",
                            ItemLevel = 174,
                            Level = 60,
                            Name = "Myriad",
                            Role = "Dps",
                            UserId = new Guid("00000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0030-000000000000"),
                            ArenaRating = 0.0,
                            BattlegroundRating = 0.0,
                            Class = "Warrior",
                            ItemLevel = 210,
                            Level = 60,
                            Name = "Ithaela",
                            Role = "Dps",
                            UserId = new Guid("00000000-0000-0000-0000-000000000010")
                        });
                });

            modelBuilder.Entity("Imi.Project.Api.Core.Entities.Dungeon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AvailableBosses")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Difficulty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstanceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KeyIncrease")
                        .HasColumnType("int");

                    b.Property<Guid>("LeaderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Succes")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("LeaderId");

                    b.ToTable("Dungeons");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000000"),
                            AvailableBosses = 4,
                            Date = new DateTime(2021, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Difficulty = "Heroic",
                            InstanceName = "De Other Side",
                            LeaderId = new Guid("00000000-0000-0000-0030-000000000000"),
                            Succes = true
                        },
                        new
                        {
                            Id = new Guid("00000002-0000-0000-0000-000000000000"),
                            AvailableBosses = 3,
                            Date = new DateTime(2021, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Difficulty = "Heroic",
                            InstanceName = "Mists of Tirna Scithe",
                            LeaderId = new Guid("00000000-0000-0000-0030-000000000000"),
                            Succes = true
                        },
                        new
                        {
                            Id = new Guid("00000003-0000-0000-0000-000000000000"),
                            AvailableBosses = 4,
                            Date = new DateTime(2021, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Difficulty = "Heroic",
                            InstanceName = "The Necrotic Wake",
                            LeaderId = new Guid("00000000-0000-0000-0030-000000000000"),
                            Succes = true
                        },
                        new
                        {
                            Id = new Guid("00000004-0000-0000-0000-000000000000"),
                            AvailableBosses = 4,
                            Date = new DateTime(2021, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Difficulty = "Mythic",
                            InstanceName = "Plaguefall",
                            LeaderId = new Guid("00000000-0000-0000-0009-000000000000"),
                            Succes = true
                        },
                        new
                        {
                            Id = new Guid("00000005-0000-0000-0000-000000000000"),
                            AvailableBosses = 4,
                            Date = new DateTime(2021, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Difficulty = "Mythic",
                            InstanceName = "Spires of Ascension",
                            LeaderId = new Guid("00000000-0000-0000-0009-000000000000"),
                            Succes = true
                        },
                        new
                        {
                            Id = new Guid("00000006-0000-0000-0000-000000000000"),
                            AvailableBosses = 4,
                            Date = new DateTime(2021, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Difficulty = "Mythic+ 5",
                            InstanceName = "Halls of Atonement",
                            KeyIncrease = 2,
                            LeaderId = new Guid("00000000-0000-0000-0011-000000000000"),
                            Succes = true
                        },
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0000-000000000000"),
                            AvailableBosses = 5,
                            Date = new DateTime(2021, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Difficulty = "Mythic+ 7",
                            InstanceName = "Theater of Pain",
                            KeyIncrease = 1,
                            LeaderId = new Guid("00000000-0000-0000-0011-000000000000"),
                            Succes = true
                        },
                        new
                        {
                            Id = new Guid("00000008-0000-0000-0000-000000000000"),
                            AvailableBosses = 5,
                            Date = new DateTime(2021, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Difficulty = "Mythic+ 8",
                            InstanceName = "Sanguine Depths",
                            LeaderId = new Guid("00000000-0000-0000-0011-000000000000"),
                            Succes = false
                        });
                });

            modelBuilder.Entity("Imi.Project.Api.Core.Entities.DungeonCharacter", b =>
                {
                    b.Property<Guid>("DungeonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DungeonId", "CharacterId");

                    b.HasIndex("CharacterId");

                    b.ToTable("DungeonCharacter");

                    b.HasData(
                        new
                        {
                            DungeonId = new Guid("00000001-0000-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0025-000000000000")
                        },
                        new
                        {
                            DungeonId = new Guid("00000001-0000-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0019-000000000000")
                        },
                        new
                        {
                            DungeonId = new Guid("00000001-0000-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0020-000000000000")
                        },
                        new
                        {
                            DungeonId = new Guid("00000001-0000-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0022-000000000000")
                        },
                        new
                        {
                            DungeonId = new Guid("00000002-0000-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0025-000000000000")
                        },
                        new
                        {
                            DungeonId = new Guid("00000002-0000-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0019-000000000000")
                        },
                        new
                        {
                            DungeonId = new Guid("00000002-0000-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0020-000000000000")
                        },
                        new
                        {
                            DungeonId = new Guid("00000002-0000-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0022-000000000000")
                        },
                        new
                        {
                            DungeonId = new Guid("00000003-0000-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0025-000000000000")
                        },
                        new
                        {
                            DungeonId = new Guid("00000003-0000-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0019-000000000000")
                        },
                        new
                        {
                            DungeonId = new Guid("00000003-0000-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0020-000000000000")
                        },
                        new
                        {
                            DungeonId = new Guid("00000003-0000-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0022-000000000000")
                        },
                        new
                        {
                            DungeonId = new Guid("00000004-0000-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0018-000000000000")
                        },
                        new
                        {
                            DungeonId = new Guid("00000004-0000-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0015-000000000000")
                        },
                        new
                        {
                            DungeonId = new Guid("00000004-0000-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0014-000000000000")
                        },
                        new
                        {
                            DungeonId = new Guid("00000004-0000-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0013-000000000000")
                        },
                        new
                        {
                            DungeonId = new Guid("00000005-0000-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0018-000000000000")
                        },
                        new
                        {
                            DungeonId = new Guid("00000005-0000-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0015-000000000000")
                        },
                        new
                        {
                            DungeonId = new Guid("00000005-0000-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0014-000000000000")
                        },
                        new
                        {
                            DungeonId = new Guid("00000005-0000-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0013-000000000000")
                        },
                        new
                        {
                            DungeonId = new Guid("00000006-0000-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0016-000000000000")
                        },
                        new
                        {
                            DungeonId = new Guid("00000006-0000-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0029-000000000000")
                        },
                        new
                        {
                            DungeonId = new Guid("00000006-0000-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0027-000000000000")
                        },
                        new
                        {
                            DungeonId = new Guid("00000006-0000-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0021-000000000000")
                        },
                        new
                        {
                            DungeonId = new Guid("00000007-0000-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0016-000000000000")
                        },
                        new
                        {
                            DungeonId = new Guid("00000007-0000-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0029-000000000000")
                        },
                        new
                        {
                            DungeonId = new Guid("00000007-0000-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0027-000000000000")
                        },
                        new
                        {
                            DungeonId = new Guid("00000007-0000-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0021-000000000000")
                        },
                        new
                        {
                            DungeonId = new Guid("00000008-0000-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0016-000000000000")
                        },
                        new
                        {
                            DungeonId = new Guid("00000008-0000-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0029-000000000000")
                        },
                        new
                        {
                            DungeonId = new Guid("00000008-0000-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0027-000000000000")
                        },
                        new
                        {
                            DungeonId = new Guid("00000008-0000-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0021-000000000000")
                        });
                });

            modelBuilder.Entity("Imi.Project.Api.Core.Entities.Raid", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AvailableBosses")
                        .HasColumnType("int");

                    b.Property<int>("BossesKilled")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Difficulty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstanceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LeaderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LeaderId");

                    b.ToTable("Raids");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000000"),
                            AvailableBosses = 10,
                            BossesKilled = 10,
                            Date = new DateTime(2021, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Difficulty = "Heroic",
                            InstanceName = "Caste Nathria",
                            LeaderId = new Guid("00000000-0000-0000-0024-000000000000")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000000"),
                            AvailableBosses = 10,
                            BossesKilled = 10,
                            Date = new DateTime(2021, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Difficulty = "Heroic",
                            InstanceName = "Caste Nathria",
                            LeaderId = new Guid("00000000-0000-0000-0024-000000000000")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000000"),
                            AvailableBosses = 10,
                            BossesKilled = 10,
                            Date = new DateTime(2021, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Difficulty = "Heroic",
                            InstanceName = "Caste Nathria",
                            LeaderId = new Guid("00000000-0000-0000-0024-000000000000")
                        });
                });

            modelBuilder.Entity("Imi.Project.Api.Core.Entities.RaidCharacter", b =>
                {
                    b.Property<Guid>("RaidId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RaidId", "CharacterId");

                    b.HasIndex("CharacterId");

                    b.ToTable("RaidCharacter");

                    b.HasData(
                        new
                        {
                            RaidId = new Guid("10000000-0000-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0001-000000000000")
                        },
                        new
                        {
                            RaidId = new Guid("10000000-0000-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0025-000000000000")
                        },
                        new
                        {
                            RaidId = new Guid("10000000-0000-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0004-000000000000")
                        },
                        new
                        {
                            RaidId = new Guid("10000000-0000-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0016-000000000000")
                        },
                        new
                        {
                            RaidId = new Guid("10000000-0000-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0018-000000000000")
                        },
                        new
                        {
                            RaidId = new Guid("10000000-0000-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0002-000000000000")
                        },
                        new
                        {
                            RaidId = new Guid("10000000-0000-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0005-000000000000")
                        },
                        new
                        {
                            RaidId = new Guid("10000000-0000-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0008-000000000000")
                        },
                        new
                        {
                            RaidId = new Guid("10000000-0000-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0012-000000000000")
                        },
                        new
                        {
                            RaidId = new Guid("20000000-0000-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0001-000000000000")
                        },
                        new
                        {
                            RaidId = new Guid("20000000-0000-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0025-000000000000")
                        },
                        new
                        {
                            RaidId = new Guid("20000000-0000-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0004-000000000000")
                        },
                        new
                        {
                            RaidId = new Guid("20000000-0000-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0016-000000000000")
                        },
                        new
                        {
                            RaidId = new Guid("20000000-0000-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0018-000000000000")
                        },
                        new
                        {
                            RaidId = new Guid("20000000-0000-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0002-000000000000")
                        },
                        new
                        {
                            RaidId = new Guid("20000000-0000-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0005-000000000000")
                        },
                        new
                        {
                            RaidId = new Guid("20000000-0000-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0008-000000000000")
                        },
                        new
                        {
                            RaidId = new Guid("20000000-0000-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0012-000000000000")
                        },
                        new
                        {
                            RaidId = new Guid("30000000-0000-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0001-000000000000")
                        },
                        new
                        {
                            RaidId = new Guid("30000000-0000-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0025-000000000000")
                        },
                        new
                        {
                            RaidId = new Guid("30000000-0000-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0004-000000000000")
                        },
                        new
                        {
                            RaidId = new Guid("30000000-0000-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0016-000000000000")
                        },
                        new
                        {
                            RaidId = new Guid("30000000-0000-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0018-000000000000")
                        },
                        new
                        {
                            RaidId = new Guid("30000000-0000-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0002-000000000000")
                        },
                        new
                        {
                            RaidId = new Guid("30000000-0000-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0005-000000000000")
                        },
                        new
                        {
                            RaidId = new Guid("30000000-0000-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0008-000000000000")
                        },
                        new
                        {
                            RaidId = new Guid("30000000-0000-0000-0000-000000000000"),
                            CharacterId = new Guid("00000000-0000-0000-0012-000000000000")
                        });
                });

            modelBuilder.Entity("Imi.Project.Api.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRaidLeader")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWarlord")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Email = "martin.foler@mail.com",
                            IsAdmin = false,
                            IsRaidLeader = false,
                            IsWarlord = false,
                            Name = "Martin Foler",
                            Password = "MartinF@2021"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Email = "suzy.galliger@mail.com",
                            IsAdmin = true,
                            IsRaidLeader = false,
                            IsWarlord = false,
                            Name = "Suzy Galliger",
                            Password = "SuzyG@2021"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Email = "n.romanov@avengers.com",
                            IsAdmin = false,
                            IsRaidLeader = false,
                            IsWarlord = false,
                            Name = "Natasha Romanov",
                            Password = "BruceHulkyBrenner"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            Email = "superman@justiceleague.com",
                            IsAdmin = false,
                            IsRaidLeader = true,
                            IsWarlord = false,
                            Name = "Clark Joseph Kent",
                            Password = "Kal-El@DeadKrypton"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            Email = "brucewayne@wayne.com",
                            IsAdmin = false,
                            IsRaidLeader = false,
                            IsWarlord = false,
                            Name = "Bruce Wayne",
                            Password = "IamBatman"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            Email = "Tgemini@mail.com",
                            IsAdmin = false,
                            IsRaidLeader = false,
                            IsWarlord = false,
                            Name = "Tom Gemini",
                            Password = "Gemini@2021"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            Email = "geralt@witcher.com",
                            IsAdmin = false,
                            IsRaidLeader = false,
                            IsWarlord = false,
                            Name = "Geralt of Rivia",
                            Password = "Yennefer123"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            Email = "Olorin@aman.com",
                            IsAdmin = false,
                            IsRaidLeader = false,
                            IsWarlord = true,
                            Name = "Gandalf",
                            Password = "TrueWhiteWizard"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            Email = "Ellesar@gondor.com",
                            IsAdmin = false,
                            IsRaidLeader = false,
                            IsWarlord = false,
                            Name = "Aragorn",
                            Password = "Anduril@FlameOfTheWest"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            Email = "capt.america",
                            IsAdmin = false,
                            IsRaidLeader = false,
                            IsWarlord = false,
                            Name = "Captain America",
                            Password = "PeggyCarter"
                        });
                });

            modelBuilder.Entity("Imi.Project.Api.Core.Entities.Arena", b =>
                {
                    b.HasOne("Imi.Project.Api.Core.Entities.Character", "Leader")
                        .WithMany()
                        .HasForeignKey("LeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Imi.Project.Api.Core.Entities.ArenaCharacter", b =>
                {
                    b.HasOne("Imi.Project.Api.Core.Entities.Arena", "Arena")
                        .WithMany("ArenaCharacters")
                        .HasForeignKey("ArenaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Imi.Project.Api.Core.Entities.Character", "Character")
                        .WithMany("ArenaCharacters")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Imi.Project.Api.Core.Entities.Battleground", b =>
                {
                    b.HasOne("Imi.Project.Api.Core.Entities.Character", "Leader")
                        .WithMany()
                        .HasForeignKey("LeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Imi.Project.Api.Core.Entities.BattlegroundCharacter", b =>
                {
                    b.HasOne("Imi.Project.Api.Core.Entities.Battleground", "Battleground")
                        .WithMany("BattlegroundCharacters")
                        .HasForeignKey("BattlegroundId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Imi.Project.Api.Core.Entities.Character", "Character")
                        .WithMany("BattlegroundCharacters")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Imi.Project.Api.Core.Entities.Character", b =>
                {
                    b.HasOne("Imi.Project.Api.Core.Entities.User", "User")
                        .WithMany("Characters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Imi.Project.Api.Core.Entities.Dungeon", b =>
                {
                    b.HasOne("Imi.Project.Api.Core.Entities.Character", "Leader")
                        .WithMany()
                        .HasForeignKey("LeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Imi.Project.Api.Core.Entities.DungeonCharacter", b =>
                {
                    b.HasOne("Imi.Project.Api.Core.Entities.Character", "Character")
                        .WithMany("DungeonCharacters")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Imi.Project.Api.Core.Entities.Dungeon", "Dungeon")
                        .WithMany("DungeonCharacters")
                        .HasForeignKey("DungeonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Imi.Project.Api.Core.Entities.Raid", b =>
                {
                    b.HasOne("Imi.Project.Api.Core.Entities.Character", "Leader")
                        .WithMany()
                        .HasForeignKey("LeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Imi.Project.Api.Core.Entities.RaidCharacter", b =>
                {
                    b.HasOne("Imi.Project.Api.Core.Entities.Character", "Character")
                        .WithMany("RaidCharacters")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Imi.Project.Api.Core.Entities.Raid", "Raid")
                        .WithMany("RaidCharacters")
                        .HasForeignKey("RaidId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
